"""Add last_password_reset to users

Revision ID: aa42440c9348
Revises: 3f4083265f79
Create Date: 2025-06-01 21:16:34.228194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa42440c9348'
down_revision: Union[str, None] = '3f4083265f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('Company_id', sa.Integer(), nullable=False),
    sa.Column('Company_Name', sa.String(length=100), nullable=True),
    sa.Column('Company_Email', sa.String(length=50), nullable=False),
    sa.Column('Company_Phone_Number', sa.String(length=10), nullable=False),
    sa.Column('Company_Description', sa.String(length=255), nullable=True),
    sa.Column('Company_Location', sa.String(length=100), nullable=True),
    sa.Column('Company_Link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Company_id')
    )
    op.create_index(op.f('ix_Company_Company_Name'), 'Company', ['Company_Name'], unique=True)
    op.create_index(op.f('ix_Company_Company_id'), 'Company', ['Company_id'], unique=False)
    op.create_table('Major',
    sa.Column('Major_Id', sa.Integer(), nullable=False),
    sa.Column('Major_Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Major_Id'),
    sa.UniqueConstraint('Major_Name')
    )
    op.create_index(op.f('ix_Major_Major_Id'), 'Major', ['Major_Id'], unique=False)
    op.create_table('Skill',
    sa.Column('Skill_Id', sa.Integer(), nullable=False),
    sa.Column('Skill_Name', sa.String(length=50), nullable=True),
    sa.Column('Skill_Type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Skill_Id')
    )
    op.create_index(op.f('ix_Skill_Skill_Id'), 'Skill', ['Skill_Id'], unique=False)
    op.create_index(op.f('ix_Skill_Skill_Name'), 'Skill', ['Skill_Name'], unique=True)
    op.create_table('Skill_Requirements',
    sa.Column('Skill_Requirements_Id', sa.Integer(), nullable=False),
    sa.Column('Company_id', sa.Integer(), nullable=True),
    sa.Column('Skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Company_id'], ['Company.Company_id'], ),
    sa.ForeignKeyConstraint(['Skill_id'], ['Skill.Skill_Id'], ),
    sa.PrimaryKeyConstraint('Skill_Requirements_Id')
    )
    op.create_index(op.f('ix_Skill_Requirements_Skill_Requirements_Id'), 'Skill_Requirements', ['Skill_Requirements_Id'], unique=False)
    op.create_table('User',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('User_Name', sa.String(length=100), nullable=True),
    sa.Column('User_Password', sa.String(length=100), nullable=False),
    sa.Column('User_Email', sa.String(length=50), nullable=False),
    sa.Column('User_Phone_Number', sa.String(length=10), nullable=False),
    sa.Column('User_Gender', sa.String(length=10), nullable=True),
    sa.Column('User_Description', sa.String(length=255), nullable=True),
    sa.Column('User_Work_Experience', sa.Integer(), nullable=True),
    sa.Column('User_Final_Academic', sa.Enum('SD', 'SMP', 'SMA', 'D3', 'S1', 'S2', 'S3', name='academiclevel'), nullable=True),
    sa.Column('User_Picture', sa.String(length=255), nullable=True),
    sa.Column('User_Major', sa.Integer(), nullable=True),
    sa.Column('last_password_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_Major'], ['Major.Major_Id'], ),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_index(op.f('ix_User_User_Name'), 'User', ['User_Name'], unique=True)
    op.create_index(op.f('ix_User_User_id'), 'User', ['User_id'], unique=False)
    op.create_table('User_Skills',
    sa.Column('User_Skills_Id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Skill_id'], ['Skill.Skill_Id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('User_Skills_Id')
    )
    op.create_index(op.f('ix_User_Skills_User_Skills_Id'), 'User_Skills', ['User_Skills_Id'], unique=False)
    op.drop_index('ix_Skill_Requirements_Skill_Requirements_Id', table_name='skill_requirements')
    op.drop_table('skill_requirements')
    op.drop_index('ix_Skill_Skill_Id', table_name='skill')
    op.drop_index('ix_Skill_Skill_Name', table_name='skill')
    op.drop_table('skill')
    op.drop_index('ix_Company_Company_Name', table_name='company')
    op.drop_index('ix_Company_Company_id', table_name='company')
    op.drop_table('company')
    op.drop_index('fk_user_major', table_name='user')
    op.drop_index('ix_User_User_Name', table_name='user')
    op.drop_index('ix_User_User_id', table_name='user')
    op.drop_table('user')
    op.drop_table('major')
    op.drop_index('ix_User_Skills_User_Skills_Id', table_name='user_skills')
    op.drop_table('user_skills')
    op.alter_column('job_match_results', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_job_match_results_result_id'), 'job_match_results', ['result_id'], unique=False)
    op.drop_constraint('FK_job_match_results_user', 'job_match_results', type_='foreignkey')
    op.create_foreign_key(None, 'job_match_results', 'User', ['user_id'], ['User_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_match_results', type_='foreignkey')
    op.create_foreign_key('FK_job_match_results_user', 'job_match_results', 'user', ['user_id'], ['User_id'])
    op.drop_index(op.f('ix_job_match_results_result_id'), table_name='job_match_results')
    op.alter_column('job_match_results', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('user_skills',
    sa.Column('User_Skills_Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('User_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Skill_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Skill_id'], ['skill.Skill_Id'], name='user_skills_ibfk_1'),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], name='user_skills_ibfk_2'),
    sa.PrimaryKeyConstraint('User_Skills_Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_User_Skills_User_Skills_Id', 'user_skills', ['User_Skills_Id'], unique=False)
    op.create_table('major',
    sa.Column('Major_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Major_Name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('Major_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('User_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('User_Name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False),
    sa.Column('User_Password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('User_Email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('User_Phone_Number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('User_Gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('User_Description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('User_Work_Experience', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('User_Final_Academic', mysql.ENUM('SD', 'SMP', 'SMA', 'D3', 'S1', 'S2', 'S3'), nullable=True),
    sa.Column('User_Picture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('User_Major', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User_Major'], ['major.Major_id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('User_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_User_User_id', 'user', ['User_id'], unique=False)
    op.create_index('ix_User_User_Name', 'user', ['User_Name'], unique=True)
    op.create_index('fk_user_major', 'user', ['User_Major'], unique=False)
    op.create_table('company',
    sa.Column('Company_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Company_Name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Company_Email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Company_Phone_Number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('Company_Description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Company_Location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Company_Link', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Company_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Company_Company_id', 'company', ['Company_id'], unique=False)
    op.create_index('ix_Company_Company_Name', 'company', ['Company_Name'], unique=True)
    op.create_table('skill',
    sa.Column('Skill_Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Skill_Name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Skill_Type', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Skill_Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Skill_Skill_Name', 'skill', ['Skill_Name'], unique=True)
    op.create_index('ix_Skill_Skill_Id', 'skill', ['Skill_Id'], unique=False)
    op.create_table('skill_requirements',
    sa.Column('Skill_Requirements_Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Skill_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Company_id'], ['company.Company_id'], name='skill_requirements_ibfk_1'),
    sa.ForeignKeyConstraint(['Skill_id'], ['skill.Skill_Id'], name='skill_requirements_ibfk_2'),
    sa.PrimaryKeyConstraint('Skill_Requirements_Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Skill_Requirements_Skill_Requirements_Id', 'skill_requirements', ['Skill_Requirements_Id'], unique=False)
    op.drop_index(op.f('ix_User_Skills_User_Skills_Id'), table_name='User_Skills')
    op.drop_table('User_Skills')
    op.drop_index(op.f('ix_User_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_User_Name'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Skill_Requirements_Skill_Requirements_Id'), table_name='Skill_Requirements')
    op.drop_table('Skill_Requirements')
    op.drop_index(op.f('ix_Skill_Skill_Name'), table_name='Skill')
    op.drop_index(op.f('ix_Skill_Skill_Id'), table_name='Skill')
    op.drop_table('Skill')
    op.drop_index(op.f('ix_Major_Major_Id'), table_name='Major')
    op.drop_table('Major')
    op.drop_index(op.f('ix_Company_Company_id'), table_name='Company')
    op.drop_index(op.f('ix_Company_Company_Name'), table_name='Company')
    op.drop_table('Company')
    # ### end Alembic commands ###
